Add set_root method
aio-libs/aiohttp pull request #4296
Opened 2019-10-28 20:26 UTC by mosquito

## Adding `BaseTestServer.set_root` method

In our projects application running in separate task. And we have to set `_root` property for our test cases.
This improvement adding this opportunity as a separate method.

## Are there changes in behavior for the user?

No

## Related issue number

No any issue.

## Checklist

- [X] I think the code is well written
- [X] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [X] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

2019-10-28 20:59 UTC, prostomarkeloff commented
Looks useful for me.

2019-10-29 15:18 UTC, mosquito commented
@asvetlov done.

2019-10-30 16:57 UTC, asvetlov commented on aiohttp/test_utils.py
> +        raise NotImplementedError(
I think better to do nothing here instead of raising an exception

2019-10-30 16:58 UTC, asvetlov commented on aiohttp/test_utils.py
> +    def host(self) -> str:
Should these properties be a part of base class? I think so.

2019-10-30 21:41 UTC, mosquito commented on aiohttp/test_utils.py
> +                 scheme: Optional[str] = None,
Did not found any reason for using `sentinel` instead of `None`.

2019-10-30 21:42 UTC, mosquito commented on aiohttp/test_utils.py
> +        _sock = get_port_socket(self.host, self.port or 0)
prevent mypy warnings

2019-10-30 21:43 UTC, mosquito commented on aiohttp/test_utils.py
> +            self._scheme = 'https' if self._ssl else 'http'
shorter and much simpler

2019-10-31 16:22 UTC, asvetlov commented on aiohttp/test_utils.py
> +    def host(self) -> str:
Could it return `self._root.host`?

2019-10-31 16:22 UTC, asvetlov commented on aiohttp/test_utils.py
> +    def host(self) -> str:
The same for other properties.

2020-10-22 06:35 UTC, asvetlov approved these changes

2020-10-22 07:14 UTC, asvetlov requested changes
Sorry, looks like the PR is broken; tests fail on the current master.

Please fix them.
Otherwise, I have to close the PR.

Sorry again, I should review faster to prevent such situations.

2020-10-23 13:54 UTC, mosquito commented
It is still needed, but there are too many conflicts in it and I just close it. Sadly, I still need to change the underscored property in our projects.

2020-10-23 13:54 UTC, closed without merging

2020-10-23 17:10 UTC, asvetlov commented
Please feel free to publish an updated PR version