Make DEFAULT_LIMIT monkey patchable
aio-libs/aiohttp pull request #4696
Opened 2020-04-18 02:14 UTC by spacemanspiff2007

## What do these changes do?

Currently its not possible to change DEFAULT_LIMIT.
This change allows this:
```
import aiohttp
aiohttp.streams.DEFAULT_LIMIT = 10 * aiohttp.streams.DEFAULT_LIMIT
```

## Are there changes in behavior for the user?
No

## Related issue number
https://github.com/aio-libs/aiohttp/issues/4453

## Checklist

- [ x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

2020-04-27 12:25 UTC, spacemanspiff2007 commented
@webknjaz could you review this change, too? It would fix my application from crashing.

2020-04-27 13:12 UTC, webknjaz commented on aiohttp/streams.py
> +        self._limit = limit * 2 if limit is not None else DEFAULT_LIMIT
this makes the default limit 2 times smaller

2020-05-06 08:33 UTC, spacemanspiff2007 commented
I changed it as requested - it should be possible to merge this.

2020-05-30 03:58 UTC, spacemanspiff2007 commented
Is there anything I can do to get this merged?

2020-07-02 10:03 UTC, robhaswell commented
I am another user who would like to see this functionality.

2020-10-16 13:56 UTC, asvetlov requested changes
Sorry, I don't support this PR.
If you want to change the default buffer size -- please pass the desired value into `client.get()` or a similar call instead of monkey-patching. `ClientSession` can accept the session-default value as the argument constructor as well.

Sure, it requires a bigger pull request than initially proposed but I believe that explicit way is much better.

2020-10-16 17:03 UTC, spacemanspiff2007 commented
Thank you for your reply. The crash happens when using aiohttp together with [aiohttp-sse-client](https://github.com/rtfol/aiohttp-sse-client) but I think if it's a possible Session arg this would be still fine.
A working example and finished PR would be [here](https://github.com/aio-libs/aiohttp/pull/4456), it just has to be merged.

I am just looking for any (simple) way to change the buffer so my application doesn't go down with an exception

2020-10-17 13:48 UTC, asvetlov commented
@spacemanspiff2007 sorry again, I misled you and myself by writing controversial recommendations.

To don't bother you again I've prepared a fix myself as #5065
I hope it solves your needs.

2020-10-17 13:48 UTC, asvetlov commented
Closing the PR for the sake of #5056

2020-10-17 13:48 UTC, closed without merging

2020-10-17 15:19 UTC, spacemanspiff2007 commented
Thank you very much for your efforts and for the solution!

2020-10-19 11:41 UTC, robhaswell commented
Sorry @asvetlov I must be being dumb, but I can't see how #5056 is related to the size of the line buffer?

2020-10-19 12:14 UTC, asvetlov commented
Sorry for the typo, the actual number is #5065 instead of #5056

2020-10-19 12:27 UTC, robhaswell commented
Got it. Thanks for addressing this issue.