Added final declarations to constants (#5275)
aio-libs/aiohttp pull request #5310
Opened 2020-12-05 08:40 UTC by WisdomPill

## What do these changes do?

Adds final declarations to constants

## Are there changes in behavior for the user?
Let the user know that these constants should be considered as immutable

## Related issue number
#5275

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

2020-12-05 09:22 UTC, WisdomPill commented
@asvetlov Final has been introduced since python 3.8, what to do then?

2020-12-06 14:56 UTC, asvetlov requested changes

2020-12-06 14:56 UTC, asvetlov commented on aiohttp/client.py
> +    Final,
Please import `Final` from `typing_extensions` for backward compatibility with 3.6 and 3.7

2020-12-06 14:56 UTC, asvetlov commented on aiohttp/client_ws.py
> +from typing import Any, Final, Optional
The same

2020-12-06 14:56 UTC, asvetlov commented on aiohttp/hdrs.py
> +from typing import Final, Set
typing_extensions

2020-12-06 14:56 UTC, asvetlov commented on aiohttp/http_parser.py
> +    Final,
typing_extensions

2020-12-06 14:56 UTC, asvetlov commented on aiohttp/http_websocket.py
> +from typing import Any, Callable, Final, List, Optional, Pattern, Set, Tuple, Union
typing_extensions

2020-12-06 14:56 UTC, asvetlov commented on aiohttp/payload.py
> +TOO_LARGE_BYTES_BODY: Final[int] = 2 ** 20  # 1 MB
typing_extensions

2020-12-06 14:56 UTC, asvetlov commented on aiohttp/web_fileresponse.py
> +    Final,
typing_extensions

2020-12-06 14:56 UTC, asvetlov commented on aiohttp/web_request.py
> +    Final,
typing_extensions

2020-12-06 14:56 UTC, asvetlov commented on aiohttp/web_urldispatcher.py
> +    Final,
typing_extensions

2020-12-06 14:56 UTC, asvetlov commented on aiohttp/web_ws.py
> +from typing import Any, Final, Iterable, Optional, Tuple
typing_extensions

2020-12-12 10:39 UTC, WisdomPill commented
@asvetlov can you guide on the cython error that comes up now?

2020-12-17 10:15 UTC, WisdomPill commented
@asvetlov friendly reminder, I get an error in cythonize, I do not know how to solve it

2020-12-17 10:38 UTC, asvetlov approved these changes

2020-12-17 10:42 UTC, asvetlov commented
To make CI passed please add the following line to `requirements/cython.txt`: 
```
typing_extensions==3.7.4.3  # required for parsing aiohttp/hdrs.py by tools/gen.py
```

2020-12-17 10:54 UTC, merged

2020-12-17 11:38 UTC, asvetlov commented
Thanks!