Added first fuzzers as step in OSS-Fuzz integration.
aio-libs/aiohttp pull request #5320
Opened 2020-12-07 15:46 UTC by DavidKorczynski

## What do these changes do?
Hi Maintainers,

I would like to set up continuous fuzzing of aiohttp by way of OSS-Fuzz. Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects. OSS-Fuzz recently added support for Python and it would be great to have aiohttp integrated. The only expectation of integrating into OSS-Fuzz is that bugs will be fixed. This is not a "hard" requirement in that no one enforces this and the main point is if bugs are not fixed then it is a waste of resources to run the fuzzers, which we would like to avoid.

In this PR https://github.com/google/oss-fuzz/pull/4764 I have done exactly that, namely created the necessary logic from an OSS-Fuzz perspective to integrate aiohttp. If you would like to integrate, could you please provide a set of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. The emails should be linked to a Google account in order to view the detailed reports and notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

2020-12-07 18:26 UTC, webknjaz requested changes
If accepted, this would need to add the test dependencies, integrate the runs into pytest instead of dropping-in standalone files nobody executes, and make the CI green (it's broken right now).

2020-12-07 18:32 UTC, DavidKorczynski commented
Thanks for the response @webknjaz 

I would be happy to do those aspects as long as aiohttp would like to integrate into oss-fuzz

2020-12-07 18:33 UTC, webknjaz commented
@DavidKorczynski I don't see any reason why not. But let's wait for @asvetlov to weigh in.

2020-12-07 19:22 UTC, DavidKorczynski commented
Thanks @webknjaz 

Notice here that if you prefer to not have the fuzzers in the aiohttp repository then we can also store the fuzzers in the OSS-Fuzz repository for now. However, from a long term perspective it would be great to get fuzzing into the main aiohttp repo.

2020-12-07 20:30 UTC, asvetlov commented
I support the idea in general but should learn about OSS-Fuzz more.
I've started by reading https://github.com/google/oss-fuzz README.
From my understanding, fuzzers can help with finding programming errors related to Python C Extensions. 
Is it correct?
Maybe you can point on resources that are good starters?
How is it integrated, how can I get a feedback from fuzzing runs, what should we do to write really good and useful fuzzers, what is the fuzzers maintenance procedure, etc., etc.?

Fuzzers can live in aiohttp repo, I see no problem with it.
My email is andrew.svetlov@gmail.com

2021-01-26 20:19 UTC, DavidKorczynski commented
@asvetlov

Fuzzers have traditionally been used for native code as a way of catching memory corruption bugs and alike. However, recently there has been a move to more languages, e.g. Go, Rust and Python. When fuzzing pure python apps (no native code) the general bug you will be looking for are unhandled execptions, e.g. if function F promises to throw exceptions from the set X fuzzers can be used to try and break things and determine whether function F can ever throw an exception outside the promised set X. These types of bugs are closer to reliability bugs, but still crucial.

The specific fuzzer we will be using in this context is Atheris: https://github.com/google/atheris This is a good place to start for understanding fuzzing in a Python context. 

I also created a small video that shows how the Atheris fuzzer works here: https://www.youtube.com/watch?v=Wjjlk_W7WFo

The way this is integrated is by having a set of files over in the OSS-Fuzz repository, that essentially builds and runs the fuzzers in a continuous manner. Once this gets merged, a way of running this by way of OSS-Fuzz will be the following simple commands:

```
git clone https://github.com/google/oss-fuzz
cd oss-fuzz
python3 infra/helper.py build_image aiohttp
python3 infra/helper.py build_fuzzers aiohttp
python3 infra/helper.py run_fuzzer aiohttp fuzz_http_parser
```

The specific fuzzers do not need a lot of maintenance, the main thing will be fixing the bugs when they happen. They way to write really good fuzzers is, from a high-level perspective, writing fuzzers that hit high-level functions such that the coverage-guided aspects of the fuzzer will make it reach far through the code. 

You will get a ton of feedback about the status of the fuzzers, e.g. statistics, open crashes, input to trigger crashes, stack traces, fixed crashes, etc. from oss-fuzz.com. You will be able to login there and see all of it. In addition to this you will get emails whenever a crash is found.

2022-08-10 09:48 UTC, DavidKorczynski commented
Status update following https://github.com/aio-libs/aiohttp/issues/6772#issuecomment-1210415458 is I will be looking revive this PR in the coming days.

2026-06-09 19:05 UTC, Dreamsorcerer commented
@DavidKorczynski Looking to revive this. Does #12887 look right for CI integration?

Is the idea of this PR that we can maintain the fuzzers in our repo and drop them from the oss-fuzz repo? It appears the current version fails on master due to a missing parameter currently.

2026-09-05 02:45 UTC, closed without merging