Feature: Add trace_request_ctx for WS connections
aio-libs/aiohttp pull request #6761
Opened 2022-05-19 18:46 UTC by mario-purestake

## What do these changes do?

Adding the possibility to pass `trace_request_ctx` when openingn a Websocket connection. It's supported for all HTTP requests, but for some reason it was not an option for this method.

## Are there changes in behavior for the user?

The argument is optional, so it shouldn't affect the current behavior of the method.

## Related issue number

None

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

2023-04-04 18:11 UTC, cakiralpx commented
I also need this feature. Because if there's an exception to the websocket request, there's no way to retrieve the response body. The only way is to send a mutable object with `trace_request_ctx` and retrieve the data from it.
Plus, since the trace configs that are passed with `ClientSession` work the same with `ws_connect` requests, `ws_connect` function not having `trace_request_ctx` param is clearly a missing implementation detail which needs a bug fix as soon as possible.

2024-01-29 01:19 UTC, webknjaz commented on CHANGES/6761.feature
> +Add `trace_request_ctx` argument for `ws_connect` function replicating the behavior of the other requests.
https://docs.aiohttp.org/en/stable/contributing.html#adding-change-notes-with-your-prs

2024-01-29 01:20 UTC, webknjaz commented
@bdraco I think you work with websockets regularly? Mind reviewing?

2024-01-29 01:22 UTC, bdraco commented
I'm traveling this week but I'll take a look at the end of the week or if I get some free time in between flights

2024-02-01 19:12 UTC, bdraco requested changes
I think this will be fine, but it could use a test to exercise this path.

2026-05-01 19:27 UTC, closed without merging